### ISSUE TITLE
Clarification needed in (Create) "Careers in Computer Technology" 

### ISSUE THREAD

**Issue by James-Lian** [johnfraserss/TEJ2O#1]
Here is an excerpt from the Create section of "Careers in Computer Technology".

- Explain how your visual works (what items mean, etc.).
- **Explain what you envision the world to be like in 50 years if no action is taken now.**

Since the second line can be confusing, I believe a better line could be: "Explain what you envision the world to be like in 50 years if no action is taken now to reduce e-waste."

**Comment by mrseidel** [comment]
Sentence that you noted in the wiki has been updated to the following:

> Explain what you envision the world to be like in 50 years if no action is taken now regarding the manufacturing, consumption, and disposal of, technological and electronic goods.

Leaving this issue open for discussion for 24 hours.
